## Example config file.
bot:

  # The token to use to log in.
  token: <your token>

  # Weather API Key, found at http://openweathermap.org/appid
  OWMKey: <your key>

  # Command prefix
  command_prefix: <your prefix>

  # Bot version
  version: <bot version>

  # Bot version codename
  codename: <codename>

  ## YOURLS API things, leave these None since you won't have these
  # YOURLS API base, example http://sho.rt/yourls-api.php
  yourls_base: None

  # YOURLS API Key
  yourls_signature: None

  ## Postgres Database information. If left to None, then message logging will be disabled.
  # Postgres DB name
  pg_name: None

  # Postgres DB user
  pg_user: None

  # Postgres DB password
  pg_pass: None

# The default log level
log_level: INFO

#Do message logging. Only enable this if you have set up Postgres.
logging: False