## Example config file.
bot:

  # The token to use to log in.
  token: <your token>

  # Weather API Key, found at http://openweathermap.org/appid
  OWMKey: <your key>

  # Command prefix
  command_prefix: <your prefix>

  # Bot version
  version: <bot version>

  # Bot version codename
  codename: <codename>

# The default log level
log_level: INFO

#Do file logging
logging: True