### Example config file.
## Bot stuff
bot:

  # The token to use to log in.
  token: <your token>

  # The token to use in developer token
  dev_token: None

  # Command prefix
  command_prefix: <your prefix>

  # Developer command prefix
  dev_prefix: None

  # Darksky Weather API Key, found by registering at https://darksky.net/dev/register
  WeatherKey: None

  # Bot version
  version: None

  # Bot version codename
  codename: None

## Postgres Database information. If left to None, then message logging/dynamic rules will be disabled.
postgres:

  # Postgres DB name
  pg_name: None

  # Postgres DB user
  pg_user: None

  # Postgres DB password
  pg_pass: None

  # Encryption Key. Leave this to None, as the bot will fill this in later.
  # Once filled, DO NOT ALTER IT! If you do, you risk breaking the bot.
  crypt_key: None

# The default log level
log_level: INFO

# Do message logging. Only enable this if you have set up Postgres.
logging: False

# Allows for per-server customisation. Only enable this if you have set up Postgres.
dynamicrules: False
